/**
 * Cloudflare Pages Function  ->  POST /affinity26/api/register
 *
 * Part of the combined deployment: static files come from dist/, and only requests to /affinity26/api/* run this code
 * (see dist/_routes.json, generated by scripts/assemble.mjs). All logic is in worker/registerProxy.js.
 *
 * Required secret (Pages project -> Settings -> Variables and Secrets):  GOOGLE_APPS_SCRIPT_ENDPOINT
 */
import { handleRegister } from "../../../worker/registerProxy.js";

export const onRequest = ({ request, env }) => handleRegister(request, env);
